{{- if .Values.project.projectRepo }}
{{- if not .Values.project.auth.safe_key }}
{{- with .Values.project.auth.ssh_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "opc-router.fullname" $) "secret" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opc-router.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
data:
  ssh-privatekey: {{ . | b64enc }}
{{- end }}
{{- end }}
{{- end }}