{{- if not .Values.webManagement.https.disable }}
{{- if .Values.webManagement.https.cert }}
{{- if .Values.webManagement.https.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "opc-router.fullname" $) "tls-secret" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opc-router.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webManagement.https.cert | b64enc }}
  tls.key: {{ .Values.webManagement.https.key | b64enc }}
immutable: true
{{- end }}
{{- end }}
{{- end }}