apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opc-router.fullname" . }}
  labels:
    {{- include "opc-router.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.containerHistoryLimit }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "opc-router.labels" . | nindent 6 }}
      {{- include "opc-router.originalSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opc-router.labels" . | nindent 8 }}
        {{- include "opc-router.originalSelectorLabels" . | nindent 8 }}
        {{- if eq .Values.image.repository "opcrouter/runtime" }}
        {{- if not .Values.mongodb.deploy }}
        {{- include "opc-router.selectorLabels" . | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opc-router.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: web-management
            {{- if eq .Values.image.repository "opcrouter/runtime" }}
            {{- if not .Values.mongodb.deploy }}
            - name: mongodb
              containerPort: 27017
              protocol: TCP
            {{- end }}
            {{- end }}
            {{- if .Values.project.redundancy.deploy }}
            - name: ready
              containerPort: 49954
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: ready
            initialDelaySeconds: {{ .Values.project.redundancy.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.project.redundancy.readinessProbe.periodSeconds }}
            {{- end }}
          # Environment variables for the opcrouter container
          env:
          # Variables for connecting a service to the mongodb if a service is specified
          {{- if .Values.mongodb.deploy }}
          - name: OR_DATABASE_CONNECTION_STRING
            value: {{ include "getMongoDB" . }}
          {{- if .Values.mongodb.auth.enabled }}
          - name: OR_DATABASE_USERNAME
            value: root
          # Loading the password for the mongodb from secret
          - name: OR_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.mongodb.auth.existingSecret }}{{ .Values.mongodb.auth.existingSecret }}{{ else }}{{ .Release.Name }}-mongodb{{ end }}
                key: mongodb-root-password
          {{- end }}
          {{- end }} 
          {{- if .Values.webManagement.auth.disable }}
          - name: OR_DISABLE_AUTH
            value: {{ .Values.webManagement.auth.disable | quote }}
          {{- else }}
          {{- with .Values.webManagement.auth.initialUser.name }}
          - name: INITIAL_USERNAME
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.webManagement.auth.initialUser.password }}
          - name: INITIAL_PASSWORD
            value: {{ . | quote }}
          {{- end }}
          {{- end }}
          - name: OR_I_ACCEPT_EULA
            value: {{ .Values.I_do_accept_the_EULA | quote }}
          # Loading environment variables specified in the values file
          {{- range .Values.envVars }}
          - name: "{{ keys . | first }}"
            value: "{{ values . | first }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Volume mount for license
          volumeMounts:
          - mountPath: /inray/
            name: inray-volume
          - mountPath: /var/log/opcrouter/
            name: log-volume
      {{- if .Values.project.projectRepo }}
      # Project repo is specified: Get and load project
      # Volume mount for the project and configuration file
          - mountPath: /data
            name: project-volume
          # Command and arguments for loading the project and configuration into the opcrouter
          command: ["/init", "dotnet", "/app/inray.OPCRouter.Service.dll", "import-project"]
          args: 
            - "--source"
            - "/data/project/{{ .Values.project.projectPath }}"
            {{- if eq .Values.image.repository "opcrouter/runtime" }}
            {{- if eq .Values.mongodb.deploy false }}
            - "--configdb"
            - "OPCRouterRuntime"
            {{- end }}
            {{- end }}
            - "--allow-clear-config"
            - "--start-service"
            {{- if .Values.project.configPath }}
            - "--runtime-configuration-filepath"
            - "/data/project/{{ .Values.project.configPath }}"
            {{- end }}
        {{- if .Values.project.autoUpdate }}
        - name: kubernetes-proxy
          image: bitnami/kubectl:latest
          # Script for setting ssh credentials and cloning the repository onto the volume
          command: ['sh', '-c', "kubectl proxy;"]
        - name: git-ops
          image: alpine/git:latest
          # Script for setting ssh credentials and cloning the repository onto the volume
          command: ["sh", "-c"]
          args:
          - >-
            {{- include "project.gitops" $ | indent 12}}
          # Volume mount for the project and configuration file
          volumeMounts:
          - mountPath: /data
            name: project-volume
          {{- if (or .Values.project.auth.ssh_key .Values.project.auth.ssh_secret) }}
          env:
          - name: PROJECT_SSH_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.project.auth.ssh_secret | default (printf "%s-%s" (include "opc-router.fullname" $) "secret" | trunc 63 | trimSuffix "-") }}
                key: project-ssh-key
          {{- end }}
        {{- end }}
      # Init container for pulling the project files
      initContainers:
      - name: pull-project
        image: alpine/git:latest
        # Script for setting ssh credentials and cloning the repository onto the volume
        command: ["sh", "-c"]
        args:
          - >-
          {{- include "project.clone" $ | indent 10}}
        # Volume mount for the project and configuration file
        volumeMounts:
        - mountPath: /data
          name: project-volume
        {{- if (or .Values.project.auth.ssh_key .Values.project.auth.ssh_secret) }}
        env:
        - name: PROJECT_SSH_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.project.auth.ssh_secret | default (printf "%s-%s" (include "opc-router.fullname" $) "secret" | trunc 63 | trimSuffix "-") }}
              key: project-ssh-key
        {{- end }}
      {{- end }}
      # Volume for the project and configuration file
      volumes:
      - name: inray-volume
        persistentVolumeClaim:
          claimName: {{ include "opc-router.inray.fullname" . }}
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ include "opc-router.log.fullname" . }}
      {{- if .Values.project.projectRepo }}
      - name: project-volume
      {{- if .Values.project.persistantVolume.deploy }}
        persistentVolumeClaim:
          claimName: {{ include "opc-router.fullname" . }}
      {{- else}}
        emptyDir: {}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}