apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opc-router.inray.fullname" . }}
  labels:
    {{- include "opc-router.labels" . | nindent 4 }}
  {{- if .Values.claims.inray.keepAfterUninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  {{- with .Values.claims.inray.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.claims.inray.capacity }}