apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  mongodb-root-password: "{{ default (include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" "{{ .Values.mongodb.auth.existingSecret }}" "Key" "mongodb-root-password")) (.Values.mongodb.auth.dbRootPassword) | b64enc}}"
  mongodb-replica-set-key: "{{ default (include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" "{{ .Values.mongodb.auth.existingSecret }}" "Key" "mongodb-replica-set-key")) (.Values.mongodb.auth.dbReplicaKeySet) | b64enc}}"