{{- if .Values.project.projectRepo }}
{{- with .Values.project.auth.ssh_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "opc-router.fullname" $) "secret" | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "opc-router.labels" $ | nindent 4 }}
type: Opaque
data:
  project-ssh-key: {{ . | b64enc }}
{{- end }}
{{- end }}