apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "opc-router.fullname" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/volume"
  claimRef:
    name: {{ include "opc-router.fullname" . }}
    namespace: {{ .Release.Namespace }}
