{{- if .Values.project.redundancy.deploy }}
{{- if .Values.project.redundancy.persistantVolume.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opc-router.redundancy.fullname" . }}
  labels:
    {{- include "opc-router.labels" . | nindent 4 }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.project.redundancy.persistantVolume.size }}
{{- end }}
{{- end }}