{{- if .Values.project.redundancy.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opc-router.redundancy.fullname" . }}
  labels:
    {{- include "opc-router.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 49954
      targetPort: ready
      protocol: TCP
      name: ready
  selector:
    {{- include "opc-router.originalSelectorLabels" . | nindent 4 }}
{{- end }}