{{- if eq .Values.image.repository "opcrouter/runtime" }}
{{- if eq .Values.mongodb.deploy false}}
{{- if .Values.mongodb.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opc-router.fullname" . }}
  labels:
    {{- include "opc-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.externalAccess.service.type }}
  ports:
    - port: {{ .Values.mongodb.externalAccess.service.port }}
      {{- with first .Values.mongodb.externalAccess.service.nodePorts }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: opcrouter
      protocol: TCP
      name: opcrouter
  selector:
    {{- include "opc-router.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}